packages:
  - 'packages/*'
  - playground
  - docs
catalog:
  '@ant-design/v5-patch-for-react-19': ^1.0.3
  '@ant-design/x': ^1.0.5
  '@tiptap/extension-bubble-menu': ^2.27.2
  '@tiptap/extension-underline': ^2.27.2
  '@tiptap/pm': ^2.27.2
  '@tiptap/starter-kit': ^2.27.2
  '@tiptap/vue-3': ^2.27.2
  '@types/three': ^0.182.0
  gsap: ^3.14.2
  nanoid: ^5.1.6
  three: ^0.182.0
  veaury: ^2.6.3
  vue-component-type-helpers: ^3.2.4
  vue-draggable-plus: ^0.6.1
