packages:
  - 'packages/*'
  - playground
  - docs
catalog:
  '@ant-design/v5-patch-for-react-19': ^1.0.3
  '@ant-design/x': ^1.2.0
  '@tiptap/extension-bubble-menu': ^2.11.9
  '@tiptap/extension-underline': ^2.11.9
  '@tiptap/pm': ^2.11.9
  '@tiptap/starter-kit': ^2.11.9
  '@tiptap/vue-3': ^2.11.9
  '@types/three': ^0.176.0
  gsap: ^3.13.0
  nanoid: ^5.1.5
  three: ^0.176.0
  veaury: ^2.6.2
  vue-component-type-helpers: ^2.2.10
  vue-draggable-plus: ^0.6.0
