name: Node.js Package

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Setup JS
        uses: sxzz/workflows/setup-js@v1
        with:
          fetch-all: true

      - name: Build
        run: pnpm build
        env:
          NODE_OPTIONS: --max-old-space-size=6144

      - name: Publish Beta
        if: contains(github.event.release.name, 'beta') == true
        run: pnpm publish -r --access public --no-git-checks --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        if: contains(github.event.release.name, 'beta') == false
        run: pnpm publish -r --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
