name: Node.js Package

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2

      - name: Use Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Build
        run: |
          pnpm install
          pnpm build
        env:
          NODE_OPTIONS: --max-old-space-size=6144

      - name: Publish Beta
        if: contains(github.event.release.name, 'beta') == true
        run: pnpm publish -r --access public --no-git-checks --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        if: contains(github.event.release.name, 'beta') == false
        run: pnpm publish -r --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
