name: Node.js Package

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2

      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Build
        run: |
          pnpm install
          pnpm build

      - name: Publish
        run: pnpm publish -r --access public --publish-branch main -otp ${{secrets.NPM_TOKEN}}
